apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: monitoring
  labels:
    app: httpd
spec:
  selector:
    app: httpd
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 31010
    targetPort: 80
  - name: https
    nodePort: 30774
    port: 443
    targetPort: 443
  - name: metrics
    nodePort: 30775
    port: 9117
    targetPort: 9117
